services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: guardian
        container_name: guardian
        restart: unless-stopped
        ports:
            - "8020:8000"
        volumes:
            - /usr/share/nginx/:/etc/nginx/ssl/:ro
